### ISSUE TITLE
time out when using autodiscover

### ISSUE THREAD

**Issue by msabaterlozano** [ecederstrand/exchangelib#1112]
**Describe the bug**
When attempting to login using the autodiscover feature, the library returns a timeout

**To Reproduce**

    account = Account(account_name, credentials=credentials, autodiscover=True)
    for item in account.inbox.all().order_by('-datetime_received')[:10]:
        print('hello')

the system shows
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='autodiscover-s.outlook.com', port=443): Read timed out. (read timeout=10)

**Additional context**

The timeout specified in autodiscover/protocol.py  should be increased to 30, or a way to set it via configuration should be implemented

**Comment by ecederstrand** [comment]
We want the timeout to be fairly short because the autodiscover process can easily visit 5-10 servers before finding the correct one. Each one may time out.

You can customize the timeout with the `AutodiscoverProtocol.TIMEOUT` attribute: https://github.com/ecederstrand/exchangelib/blob/7533ac640097f8111779681d7bd8dab3592fd60c/exchangelib/autodiscover/protocol.py#L7

That said, it looks like you're connecting to a mailbox hosted on O365. IT you already know the mailbox is hosted there, there's no reason to be doing any autodiscovery.

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if the above does not solve your issue.
