### ISSUE TITLE
Connection not being retried when EWS server throttling in place

### ISSUE THREAD

**Issue by champlin2** [ecederstrand/exchangelib#1139]
We use exchangelib from our automated pytest testing framework and have it kick off jobs that push data into EWS mail files and then use exchangelib to check that the results are accurate.  Our pytest framework for one product consists of four python files each that sets up the Account object the same way:

```python
credentials = OAuth2Credentials(
    client_id=oauthparams.client_id,
    client_secret=oauthparams.client_secret,
    tenant_id=oauthparams.tenant_id,
    identity=Identity(primary_smtp_address=oauthparams.smtp_address)
)
config = Configuration(
    retry_policy=FaultTolerance(max_wait=3600), 
    credentials=credentials, 
    auth_type=OAUTH2, 
    service_endpoint="https://outlook.office365.com/EWS/Exchange.asmx",
    version=Version(build=EXCHANGE_O365)
)
account= Account(
    primary_smtp_address=oauthparams.smtp_address,
    config = config,
    access_type=IMPERSONATION
)
```

This works fine for all of the tests in the first three py files but by the time we start executing the tests in the fourth file EWS has started throttling our sessions because of the activity we are having to the mail file(s) in our test tenant.  Our application handles this and it looks like exchangelib does as well except for when we get to the last file and EWS returns an SSL error which is not an error that is retryable.  The problem is I don't think there is really an SSL certificate error or the connection in the first three files wouldn't have worked either (and when I run the tests in the fourth file individually they all pass so it appears they are set up correctly).  Once the first test that hits this issue gets the error all future tests that reference this account object seem to error out as well as soon as they need to go out to EWS to get some information.  I wanted to make sure I was interpreting the output correctly and if you thought that might be the case (notice the SSL exception refers to exhausting max retries) and if there is any way to allow retries in this case?  Or would we need to manually catch this exception and retry creating the account object?

[output.txt](https://github.com/ecederstrand/exchangelib/files/9944682/output.txt)

**Comment by ecederstrand** [comment]
This one is really hard to debug. I agree that if some tests have passed, then the SSL setup on the server should be valid.

The only thing to grasp at is the `SSLError(SSLError(1, '[RSA] RSA lib (_ssl.c:2633)'))` exception, which doesn't make me much wiser in terms of what actually happened, and Google doen't return any useable hints. It's possible that the Exchange server for some reason starts to send incomplete TLS handshakes, possibly due to being heavily backlogged.

exchangelib doesn't catch and retry TLS exceptions because they are unlikely to disappear by waiting. In this case, you could retry on TLS exceptions as well. Something like this should do:

```python
import exchangelib.util

exchangelib.util.TLS_ERRORS = ()

# Create your account here
```

**Comment by champlin2** [comment]
Retrying on the TLS errors seems to work - thanks for the suggestion
