### ISSUE TITLE
How to extract the sender's email address from Mailbox

### ISSUE THREAD

**Issue by susancao** [ecederstrand/exchangelib#121]
Hello, I am trying to get the email address from the sender attribute of a message, which seem to be of the type Mailbox. May I know how I can get the url of the sender from Mailbox? the Mailbox object doesn't have an attribute for attribute '__getitem__' 

for example the Mailbox object looks like:
Mailbox('ABC', 'abc@example.com', 'OneOff', None)

How would I get abc@example.com from the object? 
This may be a stupid question, but I couldn't find the answer in the repo. Thank you in advance.

**Comment by ecederstrand** [comment]
The attribute name of the email address on a `Mailbox` object is `email_address`.

**Comment by susancao** [comment]
Thank you!

**Comment by ecederstrand** [comment]
There's a bit of magic going on with the attributes, so I don't blame you :-) All models have a `FIELDS` attribute that describes which attributes are valid on that model. See e.g. https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/properties.py#L210

**Comment by dispatchai** [comment]
Dear @ecederstrand , sorry for bringing this up again but I've spend my last few hours on this very issue which I can't take care of by self. I just need to get id, subject and the sender email, but whatever syntax I tried with Mailbox object was unsuccesful. I tried iterating too only to findout that Mailbox object is not iterable.

all_items = account.inbox.all().values('id','subject','sender')

What is the proper syntax here to get the sender email instead of the whole sender object?

**Comment by ecederstrand** [comment]
@dispatchai You cannot tell EWS to only return the email address of the sender instead of the sender object. You'll have to extract the email address client-side:

```python
for id, subject, sender in account.inbox.all().values('id','subject','sender'):
    print(id, subject, sender.email_address)
```

**Comment by kiranbeethoju** [comment]
```

acnt = Account(...)
maildir = acnt.root / 'Top of Information Store'
mcc = maildir / 'MCC_CHAD' 
#Now I am in my directory MCC
for r in mcc.all().values('id','subject','sender'):
    sub_and_sender_dict = {"sub":r["subject"], "senderMail": r["sender"].email_address}
    print(sub_and_sender_dict)
#Output would be {'sub': '2021-12-17: Daily Tasks Report: [ Source: Jira]', 'senderMail': 'mcc@callhealth.com'}    
```
