### ISSUE TITLE
 support for Read Named extended property and add message_class property to standard message properties 

### ISSUE THREAD

**Issue by shireen91** [ecederstrand/exchangelib#132]
is it possible to add messageclass of emails?

And i just want to read few of the extended properties of email.  I am unable to do it now. can you help me with it

**Comment by ecederstrand** [comment]
You can dynamically add extended properties to the Item classes you're working with. It's described in the README. You'll need to look up the magic ID's that Microsoft assigns for these properties elsewhere.

I message_class is a standard message field, we can add it easily.  I don't think exchangelib will ever support all extended properties out of the box. The more I read, the more it feels like a big mess of undocumented spaghetti. But I'm open to being convinced otherwise :-)

**Comment by ecederstrand** [comment]
Hi @shireen91 Re-reading, it's a bit unclear to me what you actually expect exchangelib to do. Can you be more explicit? Possibly with pseudo-code or other examples of what you would like to happen here?

**Comment by ecederstrand** [comment]
Closing due to submitter timeout. Please re-open if you find time to look at this again :-)
