### ISSUE TITLE
OAuth2 Support for Personal Outlook Accounts Without Azure AD

### ISSUE THREAD

**Issue by michal-dagan** [ecederstrand/exchangelib#1331]
Is your feature request related to a problem? Please describe.
Yes, the problem is that Microsoft has recently blocked Basic Authentication for Outlook.com accounts, which prevents us from using exchangelib with personal accounts (non-work or school accounts). This change has caused disruptions in our ability to access mailboxes using EWS, as we are unable to authenticate without Basic Authentication.

Describe the solution you'd like
I would like to request support for OAuth2 authentication in exchangelib specifically for personal Outlook.com accounts without requiring Azure Active Directory (Azure AD). This would allow users to authenticate using the Microsoft Identity Platform v2.0 and access their mailboxes via EWS without the need for an Azure AD application registration.

Describe alternatives you've considered
Currently, we have considered other methods to authenticate, but they are not viable solutions for personal accounts, as they do not have Azure AD associated with them. Therefore, we are left with limited options to authenticate against Outlook.com accounts.

Additional context
For more information on the deprecation of Basic Authentication and the necessity of switching to OAuth2, please refer to the Microsoft documentation: [Modern authentication methods now needed](https://support.microsoft.com/en-us/office/modern-authentication-methods-now-needed-to-continue-syncing-outlook-email-in-non-microsoft-email-apps-c5d65390-9676-4763-b41f-d7986499a90d).

**Comment by ecederstrand** [comment]
OAuth support has been in exchangelib for years. The docs contain some sections on different ways of authenticating with Office365 accounts, depending on your needs: https://ecederstrand.github.io/exchangelib/ Is anything unclear there?

**Comment by ecederstrand** [comment]
I think that question is more appropriately directed at the Outlook.com support team. I don't know the ins and outs of their account tiers or configuration.

The test suite uses a personal Office365 account. I was able to log into Azure AD with those credentials. The exchangelib docs just contain the steps I needed to take to set up OAuth there.

**Comment by ecederstrand** [comment]
Did you find a solution to this issue? It would be great to have it here so others can benefit!

**Comment by claell** [comment]
@ecederstrand, I think, I ran into a similar problem.

From what I understand, Outlook.com is no longer supporting username and password authentication.

So to use a personal Outlook.com account, one seemingly has to use OAuth2 as the only supported way (?)

For that, I likely need to create an OAuth2 application. But I could only find ways how to do that in some Azure Admin panel. Is that the way that you set it up for you (create the application on an admin panel where you had access to, and then use the application from there to authenticate @outlook.com users)?

I am asking because I don't seem to have access to such an admin panel (as that seems to require some Microsoft365 Enterprise subscription)? Is there no other way to set up an OAuth2 application for that (as a non Enterprise user)?

If not, would it be possible to set up some community OAuth2 application for exchangelib, that personal users like me can use to authenticate?

**Comment by claell** [comment]
After checking a bit deeper, I probably was misusing this issue, as it is about a different topic. As the solution for my problem was not easy to find: Apparently, one needs to set up an Azure account first, refer to this guide: https://learn.microsoft.com/en-us/entra/identity-platform/quickstart-register-app?tabs=certificate.
