### ISSUE TITLE
Runaway loop, never returns

### ISSUE THREAD

**Issue by bcoover** [ecederstrand/exchangelib#16]
I have an Exchange server with misconfigured autodiscover (doesn't return a good response), and your autodiscover never returns, it just runs forever (see more below)... I have been writing Exchange code for Python for a couple of years, and I'd be happy to join your project and then I could fix issues like this.

I found the issue in your code:
_**util.py line 253**_

You are using a "while True:" loop, which is dangerous in Python, I had some similar issues with my project. I recommend you put in some type of limit like:

```
max_loops = 10
i = 0
while i < max_loops:
    i += 1
    # do stuff
```

**Comment by ecederstrand** [comment]
Thanks for your comments! The loop in `post_ratelimited()` actually does have a safeguard; have a look at the `max_wait` and `max_redirects` values. If those two don't cover all possible paths in the code, please let me know.

What you're probably seeing is an artifact of the very large `max_wait` value. If a request fails, the loop will wait for increasing amounts of time, up to 1 hour, before bailing. The reason for this is that in my experience servers often malfunction for short periods of time, either because of migrations, maintenance tasks, misconfigurations or heavy load, or because the connecting user has hit a throttling policy limit.

If the loop exited early, consumers of exchangelib that don't implement their own rate-limiting code could quickly swamp such a server with new requests. That would only make things worse. Instead, it's better if the request loop waits patiently until the server is functioning again.

If the connecting user has hit a throttling policy, then the server will only respond with a HTTP 401, as if the password is wrong. The only cure is to stop making requests. There is no other indication AFAIK, so the code can't distinguish between the two situations.

Anyway, I'd be happy for any contributions to the project!

**Comment by ecederstrand** [comment]
Please re-open if you still think this is a bug.
