### ISSUE TITLE
How to Filter By Sender

### ISSUE THREAD

**Issue by wboling** [ecederstrand/exchangelib#169]
So, I'm able to search by subject, but not subject and sender.  How can I search by both using this method?

query = Q(subject='SubjectName') & Q(sender='me@me.com')
items = my_folder.filter(query)

I'm just not sure of the syntax and I've been unable to find it, but I am relatively new to python and this library.

Thanks!

**Comment by ecederstrand** [comment]
You can combine multiple keywords in one:

```python
my_folder.filter(subject='SubjectName', sender='me@me.com')
```

You can combine `Q` objects like you did, but they are unnecessary in this case.

**Comment by wboling** [comment]
So the correct keyword is 'sender'?

**Comment by ecederstrand** [comment]
The `Message` class has an attribute called `sender`, so that's at least a *valid* keyword. I'll leave it to you whether it's also the *correct* one for your task :-)

`Message` also has an `author` attribute (equivalent to the `From` element in EWS) and I don't have a clear understanding of the difference between the two.

**Comment by wboling** [comment]
Thanks for the quick responses.  This is all I need to finish this up!  Thanks for the library, it's very, very helpful!
