### ISSUE TITLE
CalendarView

### ISSUE THREAD

**Issue by amille44420** [ecederstrand/exchangelib#26]
I met an issue while using **exchangelib** as it is now. For my needs I have to process on every items from my folder (here is the calendar) including the occurrences. However, **exchangelib** does not provide a way to find items with a **[CalendarView](https://msdn.microsoft.com/en-US/library/office/aa564515%28v=exchg.150%29.aspx)** to list those occurrences but not only the master calendar item.

I believe the CalendarView to a be a major feature for the FindItem operation.

To make it work, I added an argument named **calendarview** to the service **FindItem**. If this one is provided, I won't inform the SOAP request with IndexedPageItemView beceause these two don't mix up together.

**Comment by ecederstrand** [comment]
Thanks for the report! I don't know about the `CalendarView` option to `FindItem` but this should definitely be supported. I wonder if this would best be exposed as a separate method on a calendar, instead of overloading `filter()`, i.e.:

`my_account.calendar.view(start=..., end=..., max_items=...)
`

That way, it's easier to enforce the `start` and `end` values and make it explicit what if happening. Another reason is that `filter()` may call either `GetItem` or `FindItem` depending on the search criteria and `view()` would need to always call `FindItem`.

`FindItem` does not support returning all attributes, for example the `body` is not returned. Do you know what happens if the `body` attribute is requested in a `CalendarView` call?

**Comment by amille44420** [comment]
I didn't try but I don't believe it will return the body, it just adds ups the occurrences. The request is still a  `FindItem` and the documentation specifies it won't return any of the message body formats, but to use `GetItem` instead to get it.

Indeed it would be better to use a separate method to use `CalendarView` like you suggested.
