### ISSUE TITLE
feature

### ISSUE THREAD

**Issue by loulou111** [ecederstrand/exchangelib#357]
Sorry to disturb you.
I'm a novice in this area, and till now I still not really clear what features can be achieved by running the `__init__.py` file in the tests folder? I just want to packaged this python project into an executable exe file, How should I configure the `settings.yml` file?  (especially the server?)
sorry to take up your time, looking forward to your reply.

**Comment by ecederstrand** [comment]
the `__init__.py` contains the entire test suite for this package. `settings.yml` is only needed if you want to run the tests that require access to a real Exchange server.

**Comment by loulou111** [comment]
so, can I run this _init_.py file directly on Windows system?  actually I met the following errors when I run the .py file:

----------------------------------------------------------------------
Traceback (most recent call last):
  File "__init__.py", line 315, in test_close
    self.assertEqual([p.raddr[0] for p in proc.connections() if p.raddr[0] == ip
_addr], [])
AssertionError: Lists differ: ['93.184.216.34'] != []

First list contains 1 additional elements.
First extra element 0:
'93.184.216.34'

- ['93.184.216.34']
+ []

----------------------------------------------------------------------
what's the reasons?

 And I Just want to package the project into a .exe file , which one is the aim file to exchange?

thank you very much for your answers again!!

**Comment by ecederstrand** [comment]
I don't know how you're trying to bundle the library as an executable. But I'm not sure it even makes sense to do so, because this is a library, so nothing is executed by default. It's just code you can import and piece together to create your own programs.

The test failure you're getting is because the TCP socket doesn't get cleaned up on your system, for some reason. The test is here: https://github.com/ecederstrand/exchangelib/blob/a0a84115c4949963e120b47fa15d931b2bf2a960/tests/__init__.py#L300

I haven't run tried to run the test suite on a Windows machine, so I don't know why this happens.

**Comment by loulou111** [comment]
thank you very much !!!
so I want to know that what will happen if I run the  exchangelib/tests/__init__.py file successfully?
sorry to interupt you ,thanks for your patience!

**Comment by ecederstrand** [comment]
`tests/__init__.py` is a test suite, which means it contains methods that exercise various parts of exchangelib to ensure that they are functioning correctly. It contains no functionality or end result mean for consumption by end users.

A successful run means that all the tests have passed. This is what e.g. https://travis-ci.org/ecederstrand/exchangelib checks for each commit to exchangelib.

**Comment by ecederstrand** [comment]
Closing. Feel free to re-open if you have unanswered questions :-)
