### ISSUE TITLE
'PidTagSearchKey' is already registered

### ISSUE THREAD

**Issue by SidharthPati** [ecederstrand/exchangelib#360]
Hi Erik,

I see the following exception randomly "'PidTagSearchKey' is already registered" when I try to fetch Search key for a large number of mailboxes.

When I reboot the system, this issue gets resolved. Can you please tell me a workaround to solve this?

**Comment by ecederstrand** [comment]
This is almost certainly an error in you own code. The error is only raised here:https://github.com/ecederstrand/exchangelib/blob/3e62cc98ec5e143b8b1cc43d2173f9cdd5df7050/exchangelib/items.py#L98

and only happens when `Item.register()` has been called twice on the same property without calling `deregister()` in between.

**Comment by SidharthPati** [comment]
Ok thanks for the prompt response. I will look into it.

**Comment by ecederstrand** [comment]
Closing. Feel free to re-open if you think this is an error in exchangelib :-)
