### ISSUE TITLE
meeting attendee's response update

### ISSUE THREAD

**Issue by warddebecker** [ecederstrand/exchangelib#362]
Hi, 

I am trying to get the status of an attendee for a calendar item, but these fields don't appear to update?
The response type always stays unknown.

`response_type='Unknown', last_response_time=None`

Any idea whats causing this? I want to use this data.
Do I need to force an update for these values or something?
In outlook it does give the correct status.

Best regards,
Ward

**Comment by ecederstrand** [comment]
The attendees don't update automatically when you have fetched a calendar item, but you should see the updated values for a calendar item if you call `my_calendar_item.refresh()`, or query the calendar again.

**Comment by warddebecker** [comment]
I completely kill the script and restart it, that should update it right?
response type still stays Unknown.

**Comment by ecederstrand** [comment]
Okay, then you'll have to enable debug logging and check the raw values that the server is sending. Either the values are not sent, or we aren't picking them up correctly. See https://github.com/ecederstrand/exchangelib#troubleshooting on how to do that.

**Comment by warddebecker** [comment]
In the XML structure, it also says unknown, so they don't appear to be sent properly.

![attendees_response](https://user-images.githubusercontent.com/15039036/37411196-89b5c2ea-27a2-11e8-9d5e-0f1d1c553015.png)

**Comment by ecederstrand** [comment]
I just tried this on my own account, and it does print `Accept` status for the attendees that have accepted:

```python
for item in a.calendar.view(
    start=tz.localize(EWSDateTime(2018, 3, 15)), 
    end=tz.localize(EWSDateTime(2018, 3, 16))
).only('required_attendees', 'subject'):
    print(item.subject)
    for x in item.required_attendees:
        print('\t%s (%s)' % (x.mailbox.name, x.response_type))
```

I don't know why that's not the case for you.

**Comment by warddebecker** [comment]
Tested with that code, and same issue... strange
And it does show the correct reponses in OWA
![response_outlook](https://user-images.githubusercontent.com/15039036/37414032-8e19198a-27a8-11e8-912b-3cc06ffdb509.JPG)
![response_python](https://user-images.githubusercontent.com/15039036/37414039-919279bc-27a8-11e8-95fc-985ddf487424.JPG)

**Comment by warddebecker** [comment]
Still trying to solve this, do you know of any Exchange settings that might have an influence on this?
Using O365, the account has impersonation and full rights on the mailboxes.

**Comment by ecederstrand** [comment]
https://msdn.microsoft.com/en-us/library/office/dd633669(v=exchg.80).aspx hints that the responses are maybe only available on the organizer's calendar item.

Have you checked the `optional_attendees`  field?

Apart from that, I have no idea why this is happening.

**Comment by warddebecker** [comment]
OK I think I found the problem.
I use following structure:
- I log in with a service account, and get all roomlists 
- afterwards I get all the rooms in these roomlists
- I open the room mailboxes with impersonation to see all meetings of the day.
And I think that is the issue, I impersonate the room mailbox which doesn't isn't able to see the reponse information.

I tested with delegation and it appears to work. Will do some more testing but should be fine.

Thanks for your time

**Comment by prashasth** [comment]
@wdbprog @ecederstrand I am trying to develop my logic around the same issue.

Let us say "EmployeeA" send an invite to "EmployeeB" and "EmployeeC". I am trying to poll for calendar invites through "EmployeeB" mailbox. But I do not see any response in "response_type". It is just unknown. I believe it is due to the reason that "EmployeeB" is not the organizer as per your comments. 

Is there any workaround "EmployeeB" can know the responses?

**Comment by ecederstrand** [comment]
I'm not sure, but I think you would have to check the calendar item sitting in the calendar of the organizer, i.e. "EmployeeA"

**Comment by nautics889** [comment]
@ecederstrand 
I've created an event and set some account in `required_attendee`. The event displayed both in account's calendar and in calendar of my acc, everything went well so far. Once the recipient react on invitation and I fetch the event it's still has 'Unknown' response type in `Attendee` instance, exactly like it described above. 
Do I understand correct that i shall not see real status in any way without either Delegate or Impersonate permission for the account? Furthermore, even in Web UI of EWS i don't see real status from this account. So, i definitely know that recipient accepted an invitation, but when i click on event and then "Attendees" that account is displayed as "No response". 
While i was writing this i clarified that it's more question about EWS itself rather than `exchangelib`.

**Comment by ecederstrand** [comment]
If it's a question regarding the inner workings of EWS rather than how exchangelib uses EWS, than I think a dedicated EWS forum would be a better place to ask. I can't confirm what is expected and unexpected EWS behavior.

**Comment by ecederstrand** [comment]
Booking items are not part of standard EWS and are only implemented as not to break exchangelib: https://github.com/ecederstrand/exchangelib/blob/7bf720d439bebf65f5e9f2ff2900b5fa9aa6c400/exchangelib/items/calendar_item.py#L459

If you need additional support for Booking elements, you can add an improved Booking implementation in your own code.

**Comment by isaacgg** [comment]
Thanks! I've been looking but I cannot find any example on how to do this, any hints on this?

**Comment by ecederstrand** [comment]
Something like:

```python
import exchangelib.items.calendar_item
from exchangelib.fields import CharField

class MyBooking(Item): 
    ELEMENT_NAME = "Booking"

    some_field = CharField(field_uri="booking:SomeField")
    [...]

exchangelib.items.calendar_item. _Booking = MyBooking
```

You could get the actual returned fields on Booking items by inspecting the XML response document (see https://ecederstrand.github.io/exchangelib/#troubleshooting).
