### ISSUE TITLE
can't access Calendar event item attributes

### ISSUE THREAD

**Issue by waldek8** [ecederstrand/exchangelib#373]
Hi,
I've got several novice questions according accessing Calendar through _exchangelib_. I'm extracting events from meeting room's calendar.
I don't really know whom I have to address those questions, here or to my EWS administrator.

Questions are:

1. Calendar's item Subject attribute isn't real subject. It always show meeting organizers Name. Example: 
_('Subject: ', 'Name Surname | FLT ')_
Is there a way to extract real meeting subject?

2. I can't get _Body_ of an meeting. It is always _None_, even if there is a body in Outlooks Calendar event. Answer I get is always:
_('Body: ', None)_

3. I can't get _response_type_ of _Attendee_. It is always _unknown_, even if responses are shown through Outlooks calendar: 
_response_type='Unknown'_

4. Categories of event are always _None_: _('Categories: ', None)_, even if Categories (colors) are assigned for the event.

5. What Calendar item attribute in _exchangelib_ is "responsible" for showing _Private_ tag of the meeting event? 

Thank you for your help.

**Comment by ecederstrand** [comment]
1. I've seen this reported before but have no idea where the problem is. We just read the `subject` field as it's delivered by the API. It may be that your client is showing something else than the actual field contents on the Exchange server.

2. You need to show your example code here, including the version of exchangelib you tested with.

3. The `response_type` is apparently only available on the calendar item of the organizer. See https://github.com/ecederstrand/exchangelib/issues/362

4. Again, please post your code. It's also possible that the colors are not, in fact, provided by categories, but some extended property instead.

5. That would be the `sensitivity` field. Be aware of the gotcha in #342 when fetching private items of another user's calendar.

**Comment by waldek8** [comment]
Thank you, Eric.
You're right. All those attributes can be accessed only if I'm organizer of the meeting.

In other case, when connecting as meeting room, which, evidently, isn't the organizer, I can't get all desired info (_Body_, _Categories_, _Response_type_).

Will try to solve this issue with my Exchange server administrator.

**Comment by ecederstrand** [comment]
Do you need further assistance with the remaining points?

**Comment by waldek8** [comment]
Hi,
that would be all as for now.
Thanks for assistance.
