### ISSUE TITLE
Unable to access a particular calendar item

### ISSUE THREAD

**Issue by suddenraj** [ecederstrand/exchangelib#379]
```python           
account = self.connect(email_address, server=server)
i = 0
stdate = EWSDateTime.from_string(param["start"]) 
eddate = EWSDateTime.from_string(param["end"])
items = account.calendar.view(start=stdate, end=eddate)
data = []
print("Length :: "+str(len(items)))
#for item in items:
print(items[1])
```

Please find the above code ..  unable to access the particular item..

![capture](https://user-images.githubusercontent.com/3331271/38191443-6201e11e-3686-11e8-9a9a-c5389481c4d2.PNG)

**Comment by suddenraj** [comment]
i think this due to the ICS file... how to handle this ?

**Comment by ecederstrand** [comment]
Please post the error message you got, or a more complete example showing the values of `param["start"]` and `param["end"]`.

The ICS file is just an attachment. Attachments are handled fine in exchangelib, so that should not cause you any issues.

Were you hoping to find two items in the date range you searched? If not, you probably want to print `items[0]` rather than `items[1]`. `items` is 0-indexed.

**Comment by suddenraj** [comment]
err :: Error: INFO:exchangelib.fields:Encountered naive datetime 2018-03-01 15:19:35 on field last_modified_time. Assuming timezone Etc/UTC

**Comment by ecederstrand** [comment]
That's an INFO log message, not an error. It means EWS didn't return any timezone information on the value of the `last_modified_time` field, so we assume it was in UTC.

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you still have problems accessing your calendar items :-)
