### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by frennkie** [ecederstrand/exchangelib#381]
I just ran the test suite on my local machine (Win10 x64) and two tests are failing:

```
  File "[...]\tests\__init__.py", line 459, in test_generate
    self.assertDictEqual(generate_map(), CLDR_TO_MS_TIMEZONE_MAP)

-  'Antarctica/Casey': 'W. Australia Standard Time',
?                       ^^^^^^     ^

+  'Antarctica/Casey': 'Central Pacific Standard Time',
?                       ^^^    ++++ ^^^
```

```
  File "[...]\tests\__init__.py", line 306, in test_close
    self.assertEqual([p.raddr[0] for p in proc.connections() if p.raddr[0] == ip_addr], [ip_addr])

AssertionError: Lists differ: [] != ['93.184.216.34']

Second list contains 1 additional elements.
First extra element 0:
'93.184.216.34'

- []
+ ['93.184.216.34']
```

The second one seems to check whether `example.com` can not be resolved to an IP - which appears to be working now...

**Comment by ecederstrand** [comment]
Thanks. The first one was just fixed by db7ca06953e5e9d45daf0eaed263f9877c965cd6

The second one is a test whether we can close TCP connections properly. It seems not all network connections provide an actual HTTP endpoint for http://example.com. I'll see if I can change that test to be more reliable.
