### ISSUE TITLE
self.folder.account.recoverable_items_deletions is None

### ISSUE THREAD

**Issue by freenetwork** [ecederstrand/exchangelib#384]
https://github.com/ecederstrand/exchangelib/blob/39c5860a7ccb72e785ffd7436a10507265c9e565/exchangelib/items.py#L376

When i delete occurrence from range.

```python
__recurrences = account.calendar.view(start=start, end=start + timedelta(days=1))
for __rec in __recurrences:
    if "bla-bla" in __rec.categories:
        __rec.soft_delete(send_meeting_cancellations=SEND_ONLY_TO_ALL)
```

I got this

```
  File "/usr/local/lib/python3.4/dist-packages/exchangelib-1.10.7-py3.4.egg/exchangelib/items.py", line 371, in soft_delete
    self.folder = self.folder.account.recoverable_items_deletions
AttributeError: 'NoneType' object has no attribute 'account'
```

How to restore occurrence after soft_delete?

**Comment by ecederstrand** [comment]
Can you change `/usr/local/lib/python3.4/dist-packages/exchangelib-1.10.7-py3.4.egg/exchangelib/items.py` line 371 to this?:

```python
self.folder = self.account.recoverable_items_deletions
```

**Comment by freenetwork** [comment]
How to restore occurrence after soft_delete?

**Comment by ecederstrand** [comment]
I actually don't know how to restore soft-deleted occurrences. I assume they are stored in the trash folder, or maybe they can be retrieved from the original folder if you set the traversal `depth` argument to `SoftDeleted` instead of `Shallow` for the `FindItem` service. It's not exposed as part of the public API, so you'll have to do some work to set it:

https://github.com/ecederstrand/exchangelib/blob/4e8cdf25a3f70734f56201d9b8e5c12da77ff1ae/exchangelib/folders.py#L177
