### ISSUE TITLE
1.11.1 version of exchangelib displays wrong folder structure when using root.tree()

### ISSUE THREAD

**Issue by Reapka** [ecederstrand/exchangelib#392]
Hello,

This is an issue I encountered in 1.11.1 version. When I try to get the folder structure of a mailbox I have access to, I receive my personal EWS account's folder structure - as a result, I cannot set custom paths to reach items in subfolders. Basically, account.root defaults to my personal account.
I tried 1.10.7 version and everything works as expected - root.tree() displays the correct folder structure of the primary SMTP address I'm trying to work with.

**Comment by ecederstrand** [comment]
Can you please provide example code that triggers this behavior?

**Comment by dramaqueeeen** [comment]
I got the same Issue in version 1.11.1 with following code:
```
BaseProtocol.HTTP_ADAPTER_CLS = NoVerifyHTTPAdapter

credentials = Credentials(USER, PW)
config      = Configuration(credentials = credentials, 
                            service_endpoint = 'URL'
                           )

others_account = Account(primary_smtp_address='EMAIL', 
                         config = config, 
                         credentials=credentials, 
                         autodiscover=False)

print(others_account.root.tree())
```

**Comment by ecederstrand** [comment]
That doesn't make sense. Are you saying that you get the folder structure of `my_account@example.com` even though `my_account@example.com` is not defined anywhere? That should only be possible if `work_account@example.com` is an alias of `my_account@example.com`.

To debug this, you need to capture the request XML of the `GetFolder` calls for the root folder in the two situations, and compare them. See https://github.com/ecederstrand/exchangelib#troubleshooting

**Comment by SteveTapajna** [comment]
ok, had some time to dig and debug, and it seems that the last time this worked was in 1.10.7, the 3 versions in 1.11 have had this issue.  Here's what I have found and I can see what is missing in the request that is causing this to happen:

I'm seeing this also, connecting to mailbox mailboxA@server.com but logging in as mailboxB@server.com.  

>print (account.inbox.total_count)  
          returns the count of the items in the inbox of mailboxA as expected

>print ((account.root / "Top of Information Store" / "Inbox").total_count) 

          returns the count of the inbox in mailboxB which is unexpected


looks like while debugging it seems like since 1.10.7 ( 1.11.x )  

when we hit account.root, it no longer sends the account we want to look at (in this case mailboxA@server.com, and therefore defaults to mailboxB@server.com as that was the account it was logging in as) this information in the request to the server, see the missing bolded request data shown below in the 1.10.7 request below vs the 1.11.x  (btw when you look at account.inbox it still works)

ver 1.11.x

<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
<s:Header>
<t:RequestServerVersion Version="Exchange2016" />
<t:TimeZoneContext>
<t:TimeZoneDefinition Id="UTC" />
</t:TimeZoneContext>
</s:Header>
<s:Body>
<m:FindFolder Traversal="Deep">
<m:FolderShape>
<t:BaseShape>IdOnly</t:BaseShape>
<t:AdditionalProperties>
<t:FieldURI FieldURI="folder:ChildFolderCount" />
<t:FieldURI FieldURI="folder:EffectiveRights" />
<t:FieldURI FieldURI="folder:FolderClass" />
<t:FieldURI FieldURI="folder:DisplayName" />
<t:FieldURI FieldURI="folder:ParentFolderId" />
<t:FieldURI FieldURI="folder:TotalCount" />
<t:FieldURI FieldURI="folder:UnreadCount" />
</t:AdditionalProperties>
</m:FolderShape>
<m:IndexedPageFolderView BasePoint="Beginning" MaxEntriesReturned="100" Offset="100" />
<m:ParentFolderIds>
<t:DistinguishedFolderId Id="root" />
</m:ParentFolderIds>
</m:FindFolder>
</s:Body>
</s:Envelope>


ver 1.10.7

<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
<s:Header>
<t:RequestServerVersion Version="Exchange2016" />
<t:TimeZoneContext>
<t:TimeZoneDefinition Id="UTC" />
</t:TimeZoneContext>
</s:Header>
<s:Body>
<m:FindFolder Traversal="Deep">
<m:FolderShape>
<t:BaseShape>IdOnly</t:BaseShape>
<t:AdditionalProperties>
<t:FieldURI FieldURI="folder:ChildFolderCount" />
<t:FieldURI FieldURI="folder:EffectiveRights" />
<t:FieldURI FieldURI="folder:FolderClass" />
<t:FieldURI FieldURI="folder:DisplayName" />
<t:FieldURI FieldURI="folder:ParentFolderId" />
<t:FieldURI FieldURI="folder:TotalCount" />
<t:FieldURI FieldURI="folder:UnreadCount" />
</t:AdditionalProperties>
</m:FolderShape>
<m:IndexedPageFolderView BasePoint="Beginning" MaxEntriesReturned="100" Offset="0" />
<m:ParentFolderIds>
<t:DistinguishedFolderId Id="root">
**<t:Mailbox>
<t:EmailAddress>mailboxA@server.com</t:EmailAddress>
<t:RoutingType>SMTP</t:RoutingType>
<t:MailboxType>Mailbox</t:MailboxType>
</t:Mailbox>**
</t:DistinguishedFolderId>
</m:ParentFolderIds>
</m:FindFolder>
</s:Body>
</s:Envelope>

**Comment by ecederstrand** [comment]
Thanks for the very thorough debugging! I remember removing the `Mailbox` element from the `DistinguishedFolderId` but I don't remember the exact reason. Either way, there's definitely a bug that needs fixing. I'll have to do some searching in the commit messages to find a proper solution.

**Comment by ecederstrand** [comment]
I just committed a possible fix. Can you test out https://github.com/ecederstrand/exchangelib/commit/71def9d94220eb639241b6a56a164cf4b7b9b593 and let me know how it goes?

**Comment by SteveTapajna** [comment]
@ecederstrand, SUPER this WORKS! 

`print (account.inbox.total_count)  `

# returns the count of the items in the inbox of mailboxA as expected

`print ((account.root / "Top of Information Store" / "Inbox").total_count) `

# now reads the data from mailboxA instead of mailboxB
