### ISSUE TITLE
an empty Mailbox is not an error

### ISSUE THREAD

**Issue by realjo** [ecederstrand/exchangelib#4]
I have an exchange user with an empty mailbox, exchangelib generates an assertion error which is wrong IMO. Proposed change to folders.py:

```
     def get_items(self, ids):
         # get_xml() uses self.with_extra_fields. Pass this to from_xml()
-        assert len(ids)
         return list(map(
             lambda i: self.item_model.from_xml(i, self.with_extra_fields),
             GetItem(self.account.protocol).call(folder=self, ids=ids))

```

**Comment by ecederstrand** [comment]
Hi realjo,

Thanks for the report! The assertion was there because it's arguably an error to call get_items with an empty list. You simply shouldn't call get_items() if find_items() returns no items.

That said, I found out when optimizing external code that uses generators, that it can be inconvenient to know if get_items() will be called with an empty collection. I fixed this in a more robust way two weeks ago: https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/folders.py#L516

**Comment by ecederstrand** [comment]
Can you show me the code that lead to the assertion? Anonymized, of course.

**Comment by realjo** [comment]
Hello Erik,

it's a bit difficult to reproduce the condition at the moment, but I do a 
find_items upfront and did not check if the returned
list of ids was empty or not. If you say calling get_items with an empty 
list of ids is invalid then this is o.k. for me, however
returning an empty list in that case could lead to simpler code in the 
callers which need to fetch the items anyway.

Joachim






 


Joachim Koenig-Baltes
Senior Solutions Architect
Joachim.Koenig-Baltes@real.lu
+352 436522-547


REAL Solutions S.A.
33, rue d'Eich
L-1461 Luxembourg

real.lu

    



This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. If 
you have received this email in error please notify the system manager.
 Please consider the environment before printing this e-mail.

**Comment by ecederstrand** [comment]
Hi Joachim,

I just wanted to know what lead to the assertion. As I explained, find_items() is already fixed in the master branch to support calling get_items() with empty collections. If you have other issues, please open a new issue :-)
