### ISSUE TITLE
Getting an item as a json object

### ISSUE THREAD

**Issue by ampkeegan** [ecederstrand/exchangelib#409]
I've checked through the source code and I can't find that this is supported. I'm looking to export an item type (eg a calendar event) as a json object.

I've written a recursive function to go through every part of an item and convert it to a dict, but with nested item types (eg required_attendees in a calendar has an Attendees object which has a Mailbox object...) it isn't very efficient. 

Are you aware of a way to do this?

Thanks!

**Comment by ecederstrand** [comment]
`.values()` is just a way to return the query results as a `dict` instead of a class instance with attributes. It's not meant for JSON serialization.

Serialization isn't really a task for this package, but the Python `json` module does a pretty good job of guiding you to help you write a custom serializer that does what you want. See e.g. https://stackoverflow.com/a/3768975/219640
