### ISSUE TITLE
Specified object was not found in store

### ISSUE THREAD

**Issue by niclego** [ecederstrand/exchangelib#430]
I have set up my credentials, config, and account object with no problem. When I try and call account.inbox however, I get :

<img width="975" alt="screen shot 2018-06-21 at 12 55 37 pm" src="https://user-images.githubusercontent.com/10523557/41744283-3108d64c-7558-11e8-9ac2-6200a38e9e8a.png">

Any idea why this is happening? The account object has these keys:

primary_smtp_address
protocol
locale
access_type
default_timezone
version
fullname
root

Thanks,
Nick

**Comment by ecederstrand** [comment]
This could be because you don't have sufficient permissions to access the inbox folder of the account you are connecting to. But I would suggest capturing the request and response XML as described in the [troubleshooting guide](https://github.com/ecederstrand/exchangelib#troubleshooting) and check whether the error is only related to the inbox folder or happens for all folders.

**Comment by ecederstrand** [comment]
Did you manage solve this problem?

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if this was not a permissions error :-)
