### ISSUE TITLE
Please make kerberos an optional package

### ISSUE THREAD

**Issue by 007** [ecederstrand/exchangelib#465]
Please make the `kerberos` package requirement optional, at least until it's not an [experimental](https://github.com/ecederstrand/exchangelib/blob/5e36dd145a4fb0b4330a02e8c2ce2e9bcdc95ae0/CHANGELOG.md#1113) feature.

Ref #404  #452 which would both be resolved if this were optional and required explicit installation.

tl;dr: https://stackoverflow.com/a/13681679/178072

**Comment by ecederstrand** [comment]
I'm a bit hesitant because install flavours mean more code, more testing and more things that can break.

#404 and #452 are already closed and there are installation instructions for various operating systems in the README. Do you have a specific problem with the `kerberos` package that you were not able to solve?

**Comment by ecederstrand** [comment]
@007 I'm leaning towards closing this as WONTFIX, unless you have any compelling arguments to add? :-)

**Comment by 007** [comment]
From a security perspective, I don't want to ship more libraries to a production instance than I have to. Reducing any possible attack surface is [basic security practice](https://en.wikipedia.org/wiki/Attack_surface), [OWASP recommended](https://www.owasp.org/index.php/Attack_Surface_Analysis_Cheat_Sheet), and even [Microsoft-approved](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-exploit-guard/attack-surface-reduction-exploit-guard).

There have been [125 CVEs](https://www.cvedetails.com/vulnerability-list/vendor_id-42/product_id-61/MIT-Kerberos.html) against Kerberos, so it's not exactly a safe package to add without considering the trade-offs in functionality. The problem is that there is no functionality - adding the potential vulnerabilities gets me zero additional features, just maybe a bugfix or two in this package.

As it stands, Kerberos is dead weight. We're stuck on the N-1 version until we can ditch that weight, or until the features justify the potential security complications.

**Comment by ecederstrand** [comment]
I'm aware that it's good practice to only install what you use, and I agree with that general principle.

Simply counting CVEs against Kerberos is always going to be skewed because it was released in 1987, 12 years before the CVE database was even created. That's many years of security research. On the other hand, the code base is extremely complicated and probably only a handful of developers know how to implement it correctly.

However, if the objective is to discourage use of Kerberos, then for most Exchange users the alternatives are NTLM and Basic auth. NTLM has over 1.000 hits when I search in CVE (mentions, not CVE numbers, I couldn't find an easy way to do the latter), and is considered insecure and even more awful than Kerberos (newer versions of NTLM is even wrapped in Kerberos, AFAIK). And Basic auth is also considered insecure - for one, it sends passwords clear-text over the wire. Digest auth is rarely availble, at least in my experience.

So, with the given options of authenticating against an Exchange server, I would actually promote the use of Kerberos auth, rather than discourage it by not having it available in the default install. I think it would make more sense security-wise to remove the NTLM package by default, but that would probably inconvenience at least 70% of our current users.

Mind you, we may still want to remove Kerberos as a default package, I just want to make sure we're doing it for the right reasons. Let's keep the discussion open.

**Comment by 007** [comment]
Kerberos shouldn't be discouraged, just not required. CVE count is just the quickest proxy I could come up with for security, just to say it has to be considered.

I stand by my original request, to remove it by default until Kerberos support is not experimental. At that point it's reasonable to switch over to use the new features or force inclusion as a hard requirement, until then it's extra attack surface for no benefit. Maybe make the optional package `experimental` instead of `kerberos` so you'll only ever have one variant to support?

Semi-on-topic, adding `build-essentials` and python dev libraries as requirements is kinda iffy on it's own. It seems like the expectation is to ship `gcc` and similar scary tools to production, versus using them for setup and then purging. That's not on you, that's on the Python ecosystem, but it's equally weird and eyebrow-raising.

**Comment by ecederstrand** [comment]
I'm not a regular Linux user myself, but I'm pretty sure `gcc` and `build-essentials`  are only build-time requirements for the packages that ship with C extensions. They can be uninstalled afterwards. I'm not sure which of the `*-dev` packages only contain header files for compilation, and which also bring in `.so` files needed at runtime.

Many popular packages provide pre-compiled binary wheels where a compiler is not necessary, but they cannot be used on all Linux versions due to binary incompatibility.

We have no tests covering Kerberos support, so that also counts as an argument to make it optional.
