### ISSUE TITLE
Implement non-caching folder traversal

### ISSUE THREAD

**Issue by hernanfila** [ecederstrand/exchangelib#468]
Hello, 
I am trying to connect to a specific account that has a lot of folder and emails, and I get the next error:
It does not happen when I connect to a smaller account (everything works great). It seems that when it connects, it fetchs all folders and it gets stuck. I enabled debug mode to get more details:
I don't know what's useful to you, I will to show you most relevant logs:

`DEBUG:exchangelib.folders:Finding None items for xxxxxxxxx.xxxx@xxxx.com (shape: IdOnly, depth: Shallow, additional_fields: None, restriction: None)
DEBUG:exchangelib.services:EWS https://xxxxxxxxxx.xxxxxxx.xxxx/EWS/Exchange.asmx, account xxxxxxxxx.xxx@xxx.com, service FindItem: Getting items at offset 0
DEBUG:exchangelib.protocol:Server xxxxxxxxxx.xxxxxxx.xxxx: Waiting for session
DEBUG:exchangelib.protocol:Server xxxxxxxxxx.xxxxxxx.xxxx: Got session 27912
DEBUG:exchangelib.util:Session 27912 thread 3240: retry 0 timeout 120 POST'ing to https://xxxxxxxxxx.xxxxxxx.xxxx/EWS/Exchange.asmx after 10s wait
DEBUG:urllib3.connectionpool:https://xxxxxxxxxx.xxxxxxx.xxxx:443 "POST /EWS/Exchange.asmx HTTP/1.1" 200 None
DEBUG:exchangelib.util:Retry: 0
Waited: 10
Timeout: 120
Session: 27912
Thread: 3240`

`DEBUG:exchangelib.folders:Folder class <class 'exchangelib.folders.Folder'> matches container class None (Inbox)
DEBUG:exchangelib.services:EWS https://xxxxxxxxxx.xxxxxxx.xxxx/EWS/Exchange.asmx, account xxxxxxxxx.xxxx@xxxx.com, service FindFolder: Getting items at offset 24200
DEBUG:exchangelib.protocol:Server xxxxxxxxxx.xxxxxxx.xxxx: Waiting for session
DEBUG:exchangelib.protocol:Server xxxxxxxxxx.xxxxxxx.xxxx: Got session 27912
DEBUG:exchangelib.util:Session 27912 thread 3240: retry 0 timeout 120 POST'ing to https://xxxxxxxxxx.xxxxxxx.xxxx/EWS/Exchange.asmx after 10s wait
DEBUG:urllib3.connectionpool:https://xxxxxxxxxx.xxxxxxx.xxxx:443 "POST /EWS/Exchange.asmx HTTP/1.1" 200 None
DEBUG:exchangelib.util:Retry: 0
Waited: 10
Timeout: 120
Session: 27912
Thread: 3240
Auth type: <requests_ntlm.requests_ntlm.HttpNtlmAuth object at 0x0000000007447C88>
URL: https://xxxxxxxxxx.xxxxxxx.xxxx/EWS/Exchange.asmx
HTTP adapter: <exchangelib.protocol.NoVerifyHTTPAdapter object at 0x0000000007447DD8>
Allow redirects: False
Response time: 1.0
Status code: 200`
`DEBUG:exchangelib.util:Session 27912 thread 3240: Useful response from https://xxxxxxxxxx.xxxxxxx.xxxx/EWS/Exchange.asmx
DEBUG:exchangelib.protocol:Server xxxxxxxxxx.xxxxxxx.xxxx: Releasing session 27912
DEBUG:exchangelib.services:Trying API version Exchange2010_SP2 for account xxxxxxxxx.xxxx@xxxx.com
DEBUG:exchangelib.services:FindItem: Got page with next offset None (last_page True)`

This kind of log appears lot of times, I suppose it's because of big number of folders:
`DEBUG:exchangelib.folders:Folder class <class 'exchangelib.folders.Folder'> matches container class None (Inbox)`

Thank you very much

**Comment by ecederstrand** [comment]
I see a lot of debug output, but no error message or description of what is not working?

**Comment by hernanfila** [comment]
This is the error: 
  raise TransportError('Unexpected next offset: %s -> %s' % (item_count, next_offset))
TransportError: Unexpected next offset: 20300 -> 20302.

It happens arbitrary. 

I don't know if it's a more efficient way to move emails from one folder to another with a specific filter. 
The command is one an simple:
	`accountSource.bulk_move(ids=sourceAccountFolder.filter(params), to_folder=destinationAccountFolder)`

But before running that, I run this to specify the folders involved: 
`sourceAccountFolder` = accountSource.inbox / 'xx' / 'sourceFolder'
	destinationAccountFolder = accountDestination.inbox / 'xx' / 'destFolder'`

And in that command(folder assignments), the log and error occurs. It happens sometimes, I think it's because a large account and the log shows that it's trying to get ALL folders and subfolders, is that ok? Why don't going directly to involved folders?

**Comment by ecederstrand** [comment]
First, enumerating all folders is an optimization. We're getting all folders upfront, instead of getting one folder at a time, upon access. It has nothing to do with the current problem.

Second, `sourceAccountFolder.filter(params)` is going to hurt here when you have 20.000+ items because it fetches the full contents of all items, including attachments etc. A better approach would be to get only the IDs: `sourceAccountFolder.filter(params).values('item_id', 'changekey')`. This is enough to tell Exchange which items to move.

Now, regarding the actual error. When you fetch a large amount of items from a folder, which `sourceAccountFolder.filter(params)` does, we get the items in pages (chunks). The default page size is 100.  Each page gives us a list of returned items in the page, and a `next_offset` value that tells us where to start the next page.

The `Unexpected next offset: 20300 -> 20302` error means that we requested a page with 100 items starting at item 20200. The server returned 100 items, but then requested us to fetch a new page with 100 items starting at item 20302. The logical next starting point would be 20300, which is what we assert.

In this case, the assert fails. Either Exchange contains a bug where it messes up its own paging counters, or the contents of the folder changed while iterating, and Exchange doesn't make any guarantees in this case, and we just have to accept that the paging values may be inconsistent.

You could try to disable the check here to see if it lets you proceed: https://github.com/ecederstrand/exchangelib/blob/d9e7e12b6bf4aab72f36587a90eb06ea5eaea322/exchangelib/services.py#L393

But we would probably also need to get rid of the `common_next_offset` value because we would have to accept that `next_offset` can be an unpredictable value that may not be the same for all folders we are iterating.

**Comment by hernanfila** [comment]
Hi again, thank you for the filter tip, I will see what I will do about that.
But actually, the error comes when I do the assignment of the folder. I put a breakpoint and the offset error comes when I step over the folder variable sentence:
`sourceAccountFolder = accountSource.inbox / 'xx' / 'sourceFolder'`

I Appreciate very much your help.

**Comment by ecederstrand** [comment]
Oh, wow, that can almost only mean the account has more than 20.000 folders. Is that plausible?

**Comment by hernanfila** [comment]
Yes :(. You are right, the whole account has more than 20k folders. 
Thank you Erik.

**Comment by ecederstrand** [comment]
The issue here is probably almost the same as I descried above, except that it's not items being added or deleted during paging, but folders. The suggested fixes would be the same.

The folder navigation API is not optimized for so many folders. We'll fetch every single folder before you can access `accountSource.inbox` and drill down using `accountSource.inbox / 'xx' / 'sourceFolder'`. It's a decision we may want to revisit in a future version.

One thing you can do to optimize your script is call `accountSource.root.find_folder()` directly but with `depth=SHALLOW` instead. That will give you only the direct children of the root. You can then call `find_folder()` on the returned `inbox` folder, then on the `xx` folder, and so forth.

Another possibility would be to add support for filters when searching folders. [FindFolder](https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/findfolder) has a `Restriction` element, we just haven't implemented it yet. Then something like this would do what you want, with better performance: `accountSource.root.filter_folders(name='sourceFolder')`.

**Comment by hernanfila** [comment]
I will update you with comments when I try that. In the meanwhile, I upgraded to last version (1.11.14) but had problems with the connections. May I open a new Issue?
I had to downgrade and now it's working again.

The error is not pretty clear (at least for me). 
Script commands:
```
version = Version(build=Build(14, 03, 0352, 000))
config = Configuration(server='serverrr', credentials=credentials,version=version, auth_type=NTLM)
	account = Account(primary_smtp_address='mailasdf@mailasdf.com', credentials=credentials,config=config,autodiscover=False, access_type=DELEGATE)
	MyfolderX = account.inbox / 'myfolder' / 'mySubFolder'
```
Error log commands:

```
xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><m:ResponseMessages><m:GetFolderResponseMessage ResponseClass="Error"><m:MessageText>The specified folder
could not be found in the store.</m:MessageText><m:ResponseCode>ErrorFolderNotFound</m:ResponseCode><m:DescriptiveLinkKey>0</m:DescriptiveLinkKey><m:Folders/></m:GetFolderResponseMessage><m:GetFolderResponseMessage ResponseClass="Error"><m:MessageText>The specified folder could not be found in the store.
```
Last part of the error:
```
 File "C:\mypath\python27\lib\site-packages\exchangelib\services.py", line 312, in _get_elements_in_response
    container_or_exc = self._get_element_container(message=msg, name=self.element_container_name)
  File "C:\mypath\python27\lib\site-packages\exchangelib\services.py", line 287, in _get_element_container
    raise self._get_exception(code=response_code, text=msg_text, msg_xml=msg_xml)
exchangelib.errors.ErrorConnectionFailed: Connection did not succeed. Try again later.

```

I would like to highlight that the same script version in old exchangelib works.

Thank you Erik!

**Comment by hernanfila** [comment]
I will update you with comments when I try that. In the meanwhile, I upgraded to last version (1.11.14) but had problems with the connections. May I open a new Issue?
I had to downgrade and now it's working again.

The error is not pretty clear (at least for me). 
Script commands:
```
version = Version(build=Build(14, 03, 0352, 000))
config = Configuration(server='serverrr', credentials=credentials,version=version, auth_type=NTLM)
	account = Account(primary_smtp_address='mailasdf@mailasdf.com', credentials=credentials,config=config,autodiscover=False, access_type=DELEGATE)
	MyfolderX = account.inbox / 'myfolder' / 'mySubFolder'
```
Error log commands:

```
xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><m:ResponseMessages><m:GetFolderResponseMessage ResponseClass="Error"><m:MessageText>The specified folder
could not be found in the store.</m:MessageText><m:ResponseCode>ErrorFolderNotFound</m:ResponseCode><m:DescriptiveLinkKey>0</m:DescriptiveLinkKey><m:Folders/></m:GetFolderResponseMessage><m:GetFolderResponseMessage ResponseClass="Error"><m:MessageText>The specified folder could not be found in the store.
```
Last part of the error:
```
 File "C:\mypath\python27\lib\site-packages\exchangelib\services.py", line 312, in _get_elements_in_response
    container_or_exc = self._get_element_container(message=msg, name=self.element_container_name)
  File "C:\mypath\python27\lib\site-packages\exchangelib\services.py", line 287, in _get_element_container
    raise self._get_exception(code=response_code, text=msg_text, msg_xml=msg_xml)
exchangelib.errors.ErrorConnectionFailed: Connection did not succeed. Try again later.

```

I would like to highlight that the same script version in old exchangelib works.

Thank you Erik!

**Comment by ecederstrand** [comment]
Is the `ErrorConnectionFailed` exception persistent, or does it only happen sometimes?

It just occurred to me that we could use `__floordiv__` to add support for non-caching folder traversal. The syntax would be `sourceAccountFolder = accountSource.inbox // 'xx' // 'sourceFolder'` and would work without creating or touching the cache. I'm keeping this issue open to support just that.

**Comment by ecederstrand** [comment]
Restrictions are now supported for `FindFolder`. Supporting `__floordiv__` is as easy as:

```python
def __floordiv__(self, other):
    return list(FolderCollection(account=self.root.account, folders=[self])
                .find_folders(q=Q(name=other), depth=SHALLOW))[0]
```
plus error handling, tests and documentation.
