### ISSUE TITLE
Importing local .msg from disk

### ISSUE THREAD

**Issue by mr-bjerre** [ecederstrand/exchangelib#512]
Is it possible to read a local `.msg` into a `Message` instance? I can't seem to find a solution.

A workaround would require me to import local `.msg` files to a temporary folder in outlook and then start scraping. Hmmm.

**Comment by ecederstrand** [comment]
There's no standard file format for a .msg file, as far as I know. Some email clients will dump the raw MIME content of the email message. That is the equivalent of `Message.mime_content` but if you want to send the email afterwards, you need to parse the file to pick out the sender, recipients, subject, body etc.

If you want to migrate data from one Exchange account to another, have a look at the export and upload functionality: https://github.com/ecederstrand/exchangelib#export-and-upload

**Comment by mr-bjerre** [comment]
Some context:

I am scraping emails from exchange to json.

But I also want to be able to parse local `.msg` files from the disk (not on exchange) to json using the same parser. Are there any easy way to do that?

**Comment by ecederstrand** [comment]
That's not possible to answer without knowing the format of your .msg files :-) If it's raw MIME content, then have a look at https://docs.python.org/3/library/email.parser.html#email.parser.BytesParser.parse

**Comment by mr-bjerre** [comment]
Alright. I went ahead and created a script to upload the local files to exchange using `win32com`.

**Comment by cfrelet** [comment]
I have the same question actually....
I'm doing some mocking and want to simulate a Message object. 
So I saved an email locally with the attachment I want. I was thinking to create a Message object from that msg file. But maybe there is another way to create an Message object easier cause you seems to say your library doesn't have something to parse an  msg and input it into a Message object.

**Comment by ecederstrand** [comment]
I still don’t know what the format of your .msg files are. If you want to mock a message, the easiest may be to fetch a Message using exchangelib and pickle it.

**Comment by cfrelet** [comment]
Thanks for your great help as usual.

My msg is coming from outlook. I’m not sure what else necessary. I’ll take a look at https://docs.python.org/3/library/email.parser.html#email.parser.BytesParser.parse
It seems to have a way to build a Message same format as what I get from your lib.

I’m not sure how pickling works. From what I read I think you mean:
- connect to the mailbox
- extract whatever message I need
- deserialize it using pickle method
- change data I want 
- re-serialize the message again and us it to my mock function.
In my case it will not work because I’m trying to work I dependently from the connection to the mailbox for a pytest. So I just mock the connection, mock the message, extract the files I need to work from there. So I need to mock that message. 
But I’m not that familiar with mocking so maybe my way of thinking is wrong.

**Comment by cfrelet** [comment]
I believe you expect we use something like that:
```
import email
with open('C:\\temp\\test.msg', 'rb') as fp:
    msg = email.parser.BytesParser().parse(fp)
```
My issue is it doesn't create any exploitable Message object, Probably as you said the parser is not adapt to my message format....
How can I get the format?

I can explore the Message when I open it via exchangelib so maybe a field there can give me that info.

**Comment by ecederstrand** [comment]
What I was suggesting is to create a mock message from outside the test. Connect to a live server, fetch the message you want to use in a test, pickle it and save it to a file. You can then commit this file as a test fixture. When you run your test, unpickle the file into a Message object and run whatever tests you want on that Message object.
