### ISSUE TITLE
bad handshake error( ('ssl routines' 'ssl3_get_record' 'wrong version number')

### ISSUE THREAD

**Issue by guptasakshi01** [ecederstrand/exchangelib#535]
While using exchangelib module i am getting error **bad handshake error( ('ssl routines' 'ssl3_get_record' 'wrong version number')**

`config = Configuration(server='<server>:25', credentials=credentials)`

we are using :25 because server is accessible over port 25 not 443.

Tried using `BaseProtocol.HTTP_ADAPTER_CLS = NoVerifyHTTPAdapter` to ignore TLS validation.
But still recieving same error.

Please guide if i am doing anything wrong

**Comment by ecederstrand** [comment]
There is currently no way to speciy the TCP port. We just assume port 443 for HTTPS.

Are you sure EWS is being served on port 25? That port is usually reserved for the SMTP protocol.

Anyway, the error you are getting is either because the server you are connecting to doesn't support the SSL protocol, or does not support any versions of the SSL protocol that your client implements.

`NoVerifyHTTPAdapter` only disables validation of the *certificate* being served over SSL, not SSL altogether.

**Comment by guptasakshi01** [comment]
@ecederstrand  that server is using smtp protocol.

**Comment by ecederstrand** [comment]
Then you cannot use this package. We can only connect to servers running EWS.
