### ISSUE TITLE
message forward is successful even if to_recipients is some dummy or address that is not of same org.

### ISSUE THREAD

**Issue by karthikhebbar** [ecederstrand/exchangelib#576]
If i try to use 'forward' interface of message like below 
message.forward(subject='This is forwarded mail', body='', to_recipients=['dummy@dddddd.com',])
This doesn't throw any errors like ErrorNonExistentMailbox  saying it's invalid address (SMTP address has no mailbox associated with it)

**Comment by ecederstrand** [comment]
I don't think EWS will give you that kind of immediate feedback. Do you have documentation stating otherwise?

Mind you, it may take minutes (even hours if you are greylisted on the MX server of `dddddd.com`) for this kind of error message to be returned from the receiving server. This is too long time to be contained in an HTTP request.

You'll get an email in your inbox eventually with this error message. That's not an immediate action in e.g. Outlook either.

**Comment by karthikhebbar** [comment]
Thanks for clarification. Nope i haven't seen any doc. I was under assumption that it will through similar error like it does while accessing "NonExisting" mailbox. Just a question here, assuming if to_recepient  ('validuser@validdomain.com') was valid but different than current org domain  which exchange server is accepting mail for, then will mail go external user ?

**Comment by ecederstrand** [comment]
Yes, that's just like sending an email to an external email address.

**Comment by ecederstrand** [comment]
Closing since I don't this is a bug and I don't see how we could add the feature. Feel free to reopen if you think otherwise.
