### ISSUE TITLE
Directory crawling and creation issue

### ISSUE THREAD

**Issue by leonv024** [ecederstrand/exchangelib#633]
I want to copy the directory layout of one account to another and I found a solution, but it is not how I think it should be done.

The problem I had was with:
```Python
create = Folder(parent=naar_account.inbox / subfolder, name=folder)
```

It doesn't accept strings, for example:
```Python
create = Folder(parent=naar_account.inbox / "folder1/subfolder1/subfolder2", name=folder)
```

I worked around this issue by doing the following:
```Python
# Get last item, it's the dir we need to create
folder = par.split('/')[-1]

# Replace last item, it's the dir, we only need the parent
par = par.replace(par.split('/')[-1], '')[:-1]

# The code we need
code = "create = Folder(parent=naar_account.inbox / "

# Make dirs a string by quoting them
par = ' '.join('"{}" /'.format(dir) for dir in par.split('/'))[:-1]

# Run code / Create dirs
exec(code + par + ', name="%s"); create.save()' % folder)
print('[Created] %s' % folder)
```

It executes like:
```Python
create = Folder(parent=naar_account.inbox / "folder1" / "subfolder1" / "subfolder2", name=folder)
```

Ofcourse, this code runs in a loop, creating all subfolders in the process.

But is there any other way?
Am I thinking to complicated, again?

I think it's just stupid it doesn't understand a path given as string...

**Comment by ecederstrand** [comment]
It's correct that the slash notation doesn't split on slashes in the given folder name. That's because a folder name may actually contain a slash, so `a.inbox / 'A/B tests'` would become `a.inbox / 'A' / 'B tests'` which is not what the user wants.

So some kind of looping is necessary to do what you want. Given a string with slashes, I would probably just do:

```python
def create_subfolders(root, path_with_slashes):
    fld = root
    for fld_name in path_with_slashes.split('/'):
        fld = fld / fld_name
        fld.save()
    return fld

my_fld = Folder(
    parent= create_subfolders(a.inbox, "folder1/subfolder1/subfolder2",
    name='subfolder3'
).save()
```

**Comment by ecederstrand** [comment]
Also, as mentioned in https://stackoverflow.com/questions/57739419/exec-name-not-defined-but-works-earlier-on-in-the-same-code you have a bad habit of using `exec()` to build up your code. It seems you are thinking too much of code as strings of text instead of objects to be manipulated. If you find yourself having to use `exec()`, there are almost always better ways of solving your problem :-)

**Comment by leonv024** [comment]
Hehe, true..

Using `exec()` was more of a "screw it, I need this to work right now" last resort kinda option because everything i tried failed.

However, when I implement your example I get errors.

2 different errors, failing on `fld.save()` (it's crying about `str() / str()` or w/e) and some Exchange error, which doesn't make sense. I'll debug it later.

I'll take a closer look at it later this week.

Thank you for your help so far.

**Comment by ecederstrand** [comment]
I just updated the example above with some improvements and verified that it works.

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen and post stack trace or other details if the example doesn't work.
