### ISSUE TITLE
Make ConversationID, ConversationTopic, ConversationIndex fields writeable?

### ISSUE THREAD

**Issue by idovandijk** [ecederstrand/exchangelib#642]
Some questions were asked about conversation ID, I understand it is currently read-only.
Is it possible to send an email as part of a conversation (so it will be grouped together with the rest of the emails under the same conversation)?

If not, do we know of any other Python library that will allow doing that?
Thanks!

**Comment by ecederstrand** [comment]
I'm not sure the ConversationID, ConversationTopic or ConversationIndex fields *are* in fact read-only. I can't find definitive answers in https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/message-ex15websvcsotherref.

It's possible the write part just hasn't been tested to work. In that case, it would be cool if you can get it to work. A starting point would be to remove the read-only flag at https://github.com/ecederstrand/exchangelib/blob/ca29b437f49400fd3d18ec3e03a1b21a757ea7c4/exchangelib/items.py#L223

**Comment by ecederstrand** [comment]
`ConversationTopic` and `ConversationIndex` are read-only fields according to https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-work-with-conversations-by-using-ews-in-exchange I assume ConversationID is the same because it's an I generated by Exchange.

According to https://stackoverflow.com/questions/54340393/creating-a-new-email-that-is-apart-of-a-conversation-in-ews you're supposed to set the `MessageID` to the same ID as the original message in the conversation. That should tell Exchange to set the conversation fields correctly.

The same email also suggests that it's possible to forcefully set these values using the MAPI property. You may have luck fiddling with extended properties to do this, but I think it's too hacky to build this into exchangelib itself.

I'm closing this issue, but feel free to reopen if you find evidence that we can do more in this package.
