### ISSUE TITLE
(Calendar) Duplicate events when running more than one import

### ISSUE THREAD

**Issue by rodrigues8** [ecederstrand/exchangelib#660]
Good afternoon,

I am doing a project that copies calendars from one account to another, I use import () and export () for this action, but I have a problem, if I run the copy again the items are all duplicates. I am trying some ways to compare the items from the source account to the destination account if I reschedule to transfer only one incremental, but all were unsuccessful, I realized that export ends up getting different. Would you know any way to check this out?

I appreciate the help.

Kind regards.

**Comment by ecederstrand** [comment]
The only really unique thing about an item is the item ID, but items get a new ID when you export and import them. You could try the `uid` field but I don't know if it's part of the export data.

If the calendar you are importing into is empty, then you could just wipe the calendar and start over. Otherwise, you could mark the calendar items you want to export with some ID in the old calendar and look for that ID in the new calendar. You could put the ID in some field that you're not using anyway, or in an extended property.

**Comment by rodrigues8** [comment]
Good Morning,

Thank you very much for the clarifications, in my case I believe that the ideal will be to run just once or clear the calendar and go up again as recommended.

Kind regards.
