### ISSUE TITLE
Permissions on Mailbox/Folder

### ISSUE THREAD

**Issue by fury-git91** [ecederstrand/exchangelib#729]
I would like to query the permissions on the mailbox and on individual folders. Can you see which people have which rights to the mailbox or individual folders?
With the command `account.delegates` I get the following output:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "VENV_PATH\venv\lib\site-packages\exchangelib\account.py", line 625, in delegates
    return list(GetDelegate(account=self).call(user_ids=None, include_permissions=True))
  File "VENV_PATH\venv\lib\site-packages\exchangelib\services\get_delegate.py", line 18, in call
    for elem in self._pool_requests(
  File "VENV_PATH\venv\lib\site-packages\exchangelib\services\common.py", line 516, in _pool_requests
    for chunk in chunkify(items, self.chunk_size):
  File "VENV_PATH\venv\lib\site-packages\exchangelib\util.py", line 94, in chunkify
    for i in iterable:
TypeError: 'NoneType' object is not iterable
```

Permissions are definitely entered on the mailbox.

I only get my own rights displayed on the calendar folder with `account.calendar.effective_rights`. Can you also see who else has calendar rights?

**Comment by ecederstrand** [comment]
You are correct that `effective_rights` only contains the current user's rights to a folder.

You could have a look at `some_folder.permissions`. It contains the information in https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/permissionset-permissionsettype

The `TypeError` was fixed in https://github.com/ecederstrand/exchangelib/commit/9ad2e0f4a7c466267b622680b7ed6a6bd3bc57e5

**Comment by fury-git91** [comment]
@ecederstrand, thanks for the answer! `delegate` now works 👍 

I tried `permission_set` on the calendar folder, but the return is always

`PermissionSet (permissions = None, calendar_permissions = [], unknown_entries = None)`

Mailboxes with different rights for the calendar are authorized. Unfortunately, these are not displayed. I could only see the calendar rights of one mailbox with `account.delegates[0].delegate_permissions.calendar_folder_permission_level`. The return was here `Editor`. I could not query other mailboxes with rights such as `Reviewer`.

We use Exchange Server 2016 CU 14.

**Comment by ecederstrand** [comment]
Hmm. I haven't played around much with permissions and delegation.

`account.delegates` in turn calls the `GetDelegate` service without a `UserId` element (see https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/getdelegate-operation). This should have the effect of returning all delegate information.

Also, it's possible that `permission_set` information is only available on a parent folder of the folder you are looking at. You could try trversing the folder structure upwards and printing `permission_set` values of the folders you encounter. Note that we explicitly ignore `permission_set` on root folders because many users got permission errors trying to fetch that field on root folders.

**Comment by ecederstrand** [comment]
Closing. I don't think we're doing anything wrong and I have no way of testing delegate information on my test server. Feel free to reopen if you have additional insight into the problem.
