### ISSUE TITLE
how to convert eml to pst?

### ISSUE THREAD

**Issue by kexin9752** [ecederstrand/exchangelib#741]
I have got the files of eml,how I packed those eml files to pst file?
I don't have much hope for this problem，because i searching for the question too long
thank you!
Thank you for answering my last question.

**Comment by ecederstrand** [comment]
As far as I know, the .pst file format is a proprietary Microsoft file format. There are some hints in https://groups.google.com/forum/#!topic/comp.lang.python/eCPYQxAMHp4

Anyway, I'm closing this issue because I think it's out of scope for this package. Feel free to reopen if you have additional comments.

**Comment by adamwilliams07** [comment]
Right Email is an important part of our life, we recommend that you convert all emails in Microsoft Outlook from EML files to PST File format, including attachments then there is no manual way to perform this operation if you don’t make any effort. But Softaken EML to PST Converter Tool can be used to help convert multiple EML files to PST File format in seconds. With this fully automatic tool, you can easily convert files with multiple single entries in a second. Also, you don’t have to worry about data security and data issues. This application is completely safe and secure from viruses. Visit the official website to use the free demo version.
