### ISSUE TITLE
Perform query with .only() in the middle of iterating through a QuerySet?

### ISSUE THREAD

**Issue by analogdash** [ecederstrand/exchangelib#767]
Hello, I'm trying to scrape thousands of emails and on a particular email, I would get an `ErrorMimeContentConversionFailed`

From another issue, I found that a workaround is to use the `.only()` modifier to not download the `mime_content` and not raise this error. However, this is an edge case and I'd like to only invoke `.only()` when encountering that error and not for the whole QuerySet since I actually need the `mime_content`. Something like

```
for email_message in account.inbox().all():

    if hasattr(email_message, 'value'):
        if email_message.value == 'MIME content conversion failed.':
            # re-query this email_message with .only()

    # processing and loading to DB
```
 
I've thought about breaking this down into multiple passes where I only get the `id` on the first pass then I iterate over my saved ids with `.get(id=saved_id)` for better control on the second pass but `.get()` doesn't seem to support `.only()` so I still get the `ErrorMimeContentConversionFailed` because it's trying to get the whole Message. I also can't use `.filter(id__exact=saved_id)` because EWS doesn't support filtering through `id`.

Also, maybe we can get a `.defer()` method so we can exclude only the `mime_content` for this error?

Hope you can help and thanks for this package.

**Comment by ecederstrand** [comment]
`.get()` does support `.only()`, but you have to put it in front, because `.get()` does not return a QuerySet. Do this instead: `account.inbox.all().only(...).get()`.

When you iterate over the results of a QuerySet and one of the items is an Exception instance, it does not tell you which ID triggered the exception. That's unfortunate as something I think we should fix.

I also like the idea of deferred fields.

One way around this is to fetch items in two steps, as you suggested yourself:

```python
ids = list(account.inbox().all().only('id', 'changekey'))
for id, item in zip(ids, account.fetch(ids)):
    if isinstance(item, Exception):
        item = account.inbox.all().only(...).get()  # Skip the mime_content field
```

**Comment by ecederstrand** [comment]
Closing. Feel free to open a new issue if you have the need for deferred fields.
