### ISSUE TITLE
Use kerberos ticket in django to send meeting

### ISSUE THREAD

**Issue by SecretUnicorn** [ecederstrand/exchangelib#775]
Dear fellow coders,

I want to send a meeting in the name of the currently logged in User. The authentication over an apache server works flawlessly with django. I am not sure though, how to integrate the automatic SSO authentication into the connection to the exchange server to send/save the meeting.

This is the apache config

```
AuthType Kerberos
AuthName "Kerberos authenticated intranet"
KrbAuthRealms  MY.DOMAIN.TLD
KrbServiceName HTTP/servername.my.domain.tld
Krb5Keytab /etc/krb5.keytab
KrbMethodNegotiate On
KrbMethodK5Passwd On
KrbLocalUserMapping On
require valid-user
```

**Comment by ecederstrand** [comment]
This question doesn't have anything to do with exchangelib. It would be better directed at a Kerberos-specific forum.

Since you are terminating the Kerberos authentication in Apache, Django just has a `REMOTE_USER`, but no ticket for the user.

It's not clear to me whether the Exchange also uses Kerberos as its authentication mechanism?

If it does, then exchangelib must have access to a valid Kerberos ticket to create a connection to the remote server. As far as I know Kerberos, you can either connect to Exchange as the `REMOTE_USER` or as a service user:

1. Have your KDC admins create a Kerberos service user that has the powers to create a Kerberos ticket on behalf of other users. This will enable you to create a ticket for `REMOTE_USER` and connect to Exchange as this account. It's also a massive security hole and breaches several security best-practices.
1. Create a service user for Exchange that is able to impersonate any account on Exchange, and use that service user to log on  to Exchange and act on behalf of `REMOTE_USER`.

If your Exchange server does not use Kerberos authentication, then the only sane option is 2) from above, using whatever authentication mechanism your Exchange server supports.

**Comment by SecretUnicorn** [comment]
Thank you for the fast response even though this was admittedly the wrong place to ask ;)
