### ISSUE TITLE
Docs index is unreadable on mobile

### ISSUE THREAD

**Issue by spotlesstofu** [ecederstrand/exchangelib#776]
First, thanks for closing #754!

[The documentation index](https://ecederstrand.github.io/exchangelib/) has overlapping sections if you open it on a small screen. 

Screenshot below.

![IMG-1781](https://user-images.githubusercontent.com/50714878/86102790-43109680-babc-11ea-8dab-c228890565b9.jpg)

**Comment by ecederstrand** [comment]
Eww, that's ugly. The "minimal" theme default page handles this much better: https://orderedlist.com/minimal/

I added some custom css in https://github.com/ecederstrand/exchangelib/blob/master/docs/assets/css/style.scss to get a wider righ-hand column because it wasn't wide enough for the boxes with example code. I may have broken the layout on small screens along the way.

**Comment by ecederstrand** [comment]
This should be fixed aft era series of commits ending in https://github.com/ecederstrand/exchangelib/commit/5e9ca047676f51211aa40e2ae6d65c028ee741f5
