### ISSUE TITLE
AttributeError in ewsdatetime.py -> from_datetime

### ISSUE THREAD

**Issue by pieterdp** [ecederstrand/exchangelib#824]
When creating an EWSDateTime using from_datetime with a datetime with timezone information, we get an AttributeError indicating that the d.tzinfo object (which is a string) does not have a key attribute.

The solution is probably checking for .key and if it is not present, using d.tzinfo instead of d.tzinfo.key.

```
File "/opt/app-root/lib/python3.6/site-packages/exchangelib/ewsdatetime.py", line 109, in from_datetime
    tz = EWSTimeZone(d.tzinfo.key)
AttributeError: 'Europe/Brussels' object has no attribute 'key'
```

**Comment by ecederstrand** [comment]
The problem here is that we want `from_datetime()` to return an `EWSDateTime` instance with a `tzinfo` attribute that is a `EWSTimeZone` instance. in the latest release, `from_datetime()` expects the input to already have a `EWSTimeZone` timezone. That may be a bit restrictive, but it's not a trivial fix.

What kind of timezone implementation is the `tzinfo` attribute of the input to `from_datetime()`?

**Comment by ecederstrand** [comment]
Actually, it wasn't too bad. Can you try our the references PR?

**Comment by pieterdp** [comment]
Hello,

I'm sorry it took this long, but I can confirm this works.

Regards,

Pieter

**Comment by ecederstrand** [comment]
Thanks for the feedback. And no worries, I wasn't impatient. I just decided the fix was probably what you needed, and I'd like to get a release out later today.
