### ISSUE TITLE
Search + unread emails

### ISSUE THREAD

**Issue by ninSmith** [ecederstrand/exchangelib#83]
Hi there,    

I don't understand how to search and filter for emails.   

Could you please provide me some examples ?

Thanks in advance.

**Comment by AltruisConsulting** [comment]
Not sure how much background you need, so will start at the beginning. This is how we use the functionality and there may be better ways to do it. I will make the assumption that you are only dealing with you inbox and not any other folders. 

1. Follow the exchangelib 'read me' in order to set up you Account and Credentials objects. The instructions are spot on and should work out of the box.

```
credentials = Credentials(username='domain\user.name', password=password)

account = Account(primary_smtp_address='user@example.com', credentials=credentials,
                  autodiscover=True, access_type=DELEGATE, locale=locale.setlocale(locale.LC_ALL, ''))

```

2. With you account object you can now access your inbox and then you can search within the inbox using the 'filter' method to search for emails based on various 'item_fields'. Here are some examples:

```
unread = account.inbox.filter(is_read=False)    #returns unread emails

dog = account.inbox.filter(subject='My new dog!')   #returns email with subject of 'My new dog!'

mike = account.inbox.filter(author='mike@hamburger.com')    #returns emails from your buddy Mike

```
  
The challenge is that the list of item_fields is not complete. You can find the available items in the Message class in the folders.py file. Unless I misunderstand something, a full blown search, similar to what you would perform in the little 'find' box at the top of Outlook  is not possible using exchangelib alone. 

If you are looking to search for strings in within the body email, you may need to cast a broad net and pull in a large number of emails and then iterate through them. Although, I would love to see a better way to do it. 

We use exchangelib as a mouthpiece to our email parser, so we don't use much searching or filtering beyond picking up unread emails and then moving them to various folders once they are processed. 

I hope that helps.

**Comment by ninSmith** [comment]
Thank you very much, your examples are very useful !

Do you know if it is possible, by any chance, to filter on the subject using a "contains" statement ?
Something like:

```
dog = account.inbox.filter(subject_contains='dog')
```

Thanks in advance

**Comment by AltruisConsulting** [comment]
No problem! So, I stand corrected from my previous post. As per the README:
```

 # If you need more complex filtering, filter() also accepts a Python-like search expression:
#
# items = my_folder.filter(
#       "start < '2016-01-02T03:04:05T' and end > '2016-01-01T03:04:05T' and categories in ('foo', 'bar')"
```

So, you can in fact perform more complex searches within the subject and body of emails. 

Example: 

```
items = account.inbox.filter("subject in 'dog'")      #returns all emails that contain the emails with dog in the subject line

items = account.inbox.filter("body in 'dog'")      #returns all emails that contain the emails with dog in the body of the email
```

boom!

**Comment by ninSmith** [comment]
Perfect !

Thanks a lot

**Comment by ecederstrand** [comment]
Just to follow up, the search functionality is actually pretty comprehensive. It's modeled around Django searching. I just did a cleanup pass on the README to make it easier to find: https://github.com/ecederstrand/exchangelib/blob/master/README.rst#searching

If you want to do a case-insensitive containment search, just do this:

```python
dog_items = account.inbox.filter(subject__icontains='dog')
```

This will return all messages in the inbox with a subject of e.g. `dog`, `DOG`, `Dogs bark` and `SEE THIS CUTE ANIMATED DOG GIF!!11!`

**Comment by MartinThoma** [comment]
Unread emails are not necessarily only in the inbox.

**Comment by niclego** [comment]
I have set up my credentials, config, and account object with no problem. When I try and call account.inbox however, I get :

<img width="975" alt="screen shot 2018-06-21 at 12 55 37 pm" src="https://user-images.githubusercontent.com/10523557/41742320-7e757850-7552-11e8-950f-997b7d051a9b.png">

Any idea why this is happening? The account object has these keys:

primary_smtp_address
protocol
locale
access_type
default_timezone
version
fullname
root

Thanks,
Nick

**Comment by ecederstrand** [comment]
This could be because you don't have sufficient permissions to access the inbox folder of the account you are connecting to. But I would suggest capturing the request and response XML as described in the [troubleshooting guide](https://github.com/ecederstrand/exchangelib#troubleshooting) and check whether the error is only related to the inbox folder or happens for all folders.
