### ISSUE TITLE
how to leave the original email as un-read after forward it

### ISSUE THREAD

**Issue by qinfeng** [ecederstrand/exchangelib#843]
I noticed the original email will be marked as read after it's been forwarded by using below code. I wonder how NOT to do that?

```
m1 = account.inbox.filter(subject='DailyMotivation1')[0]
m1.create_forward(m1.subject, None, [gmail_addr]).send(save_copy=False)

print(account.inbox.filter(subject='DailyMotivation1')[0].is_read) # it will show True
```

My use case is: I forward all the email for archive purpose only. Dont want to mark it as read automatically so that i will not miss any un-read email.

**Comment by ecederstrand** [comment]
I don't think this is something exchangelib does, and I don't see any options in the EWS API to configure that behavior. Are you sure that there is only one item with the subject `DailyMotivation1`? Your code doesn't check that, but it would if you use `.get()` instead of `.filter()`.

If this is indeed something the server does, then you'll have to set the is_read field back to false:

```python
item = account.inbox.get(subject='DailyMotivation1')
item. is_read = False
item.save(update_fields=['is_read'])
```

**Comment by qinfeng** [comment]
@ecederstrand , thanks for the comment. I think your assumption is right. And your suggestion works well. I will close the issue.
