### ISSUE TITLE
Autodiscover with different domain than email

### ISSUE THREAD

**Issue by DonNeelin** [ecederstrand/exchangelib#868]
Hi There,

Currently your autodiscover only tries to get the information from the email address.  There should also be a function to get the autodiscover from a domain as well.

Thanks!

**Comment by ecederstrand** [comment]
I’m not sure what you are asking for. The e-mail address is central to the autodiscover protocol, among other things because accounts on a server may be redirected to different EWS endpoints, for example in a hybrid setup.

**Comment by DonNeelin** [comment]
Thanks for getting back to me so quickly.

In our environment our autodiscover URL is not the URL of our email addresses or UPN because we have  multiple companies under one domain.

Email address is:  name@childcompany.com<mailto:name@childcompany.com>
Autodiscover is: Autodiscover.parentcompany.com

Thanks!

**Comment by ecederstrand** [comment]
That still doesn't make sense. If you look at https://docs.microsoft.com/en-us/previous-versions/office/developer/exchange-server-interoperability-guidance/hh352638%28v%3dexchg.140%29, there's no way to reliably get the EWS endpoint from just the email domain. The reason is that the autodiscover service may decide to send a response that redirects you to a new email address for you to autodiscover, and it may decide to do so depending on the email address you are autodiscovering.

It is the task of Exchange admins of `childcompany.com` to make sure that configuration exists to allow the autodiscover protocol to eventually find `autodiscover.parentcompany.com`.

**Comment by ecederstrand** [comment]
That still doesn't make sense. If you look at https://docs.microsoft.com/en-us/previous-versions/office/developer/exchange-server-interoperability-guidance/hh352638%28v%3dexchg.140%29, there's no way to reliably get the EWS endpoint from just the domain. The reason is that the autodiscover service may decide to send a response that redirects you to a

**Comment by DonNeelin** [comment]
The link that you provided shows that the autodiscover exists, which is does.  What it does not show is how you get to the autodiscover address.  In your code, I am sure that you just take the domain name of the email address and then use that to determine the autodiscover.  Microsoft allows you to provide the autodiscover address of the email as a separate field.  There should be an option to provide your own domain.

**Comment by ecederstrand** [comment]
The link I posted describes the procedures in the autodiscover protocol that the exchangelib implementation is modeled around.

I'm not sure what you mean by the "autodiscover address". The autodiscover protocol is about translating an email address to an EWS endpoint. Two different emails on *the same domain* may not point to the same EWS endpoint, which means that the domain alone is not enough.

exchangelib uses the POX autodiscover webservice for the actual communication with the autodiscover endpoint. If you look at e.g. https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/pox-autodiscover-request-for-exchange then it's clear that you need to provide the entire email address to get a response contining the EWS endpoint. The domain is not enough.

If you want to point the autodiscover procedure in a different direction than the protocol directs, then you may as well point exchangelib to the actual EWS endpoint and skip autodiscover altogether.

**Comment by ecederstrand** [comment]
I'm closing because I think this is a misunderstanding of the purpose of the autodiscover protocol. If you disagree, feel free to reopen with a clear description of what you are proposing, and how it's supposed to work.
