### ISSUE TITLE
inbox filter for the sender on email address is not working.

### ISSUE THREAD

**Issue by Ram-Muljani** [ecederstrand/exchangelib#913]
inbox filter for the sender on email address is not working.

I am tried using the following filter queries 

```python
mails = account.inbox.filter(is_read=False, sender__EmailAddress='SomeEmail@domain.com', subject__contains='Please work')[:20]

mails = account.inbox.filter(is_read=False, sender__email_address='SomeEmail@domain.com', subject__contains='Please work')[:20]

mails = account.inbox.filter(is_read=False, sender__contains='SomeEmail@domain.com', subject__contains='Please work')[:20]

mails = account.inbox.filter(is_read=False, sender='SomeEmail@domain.com', subject__contains='Please work')[:20]
```

[error log.txt](https://github.com/ecederstrand/exchangelib/files/6470379/error.log.txt)

all other filters seem to work but sender one is throwing an error.

```
	Traceback (most recent call last):
	  File "C:\Users\Ram12405\PycharmProjects\pythonProject\venv\lib\site-packages\exchangelib\util.py", line 140, in peek
		first = next(iterable)
	  File "C:\Users\Ram12405\PycharmProjects\pythonProject\venv\lib\site-packages\exchangelib\folders\collections.py", line 196, in find_items
		yield from FindItem(account=self.account, chunk_size=page_size).call(
	  File "C:\Users\Ram12405\PycharmProjects\pythonProject\venv\lib\site-packages\exchangelib\services\find_item.py", line 34, in call
		for elem in self._paged_call(
	  File "C:\Users\Ram12405\PycharmProjects\pythonProject\venv\lib\site-packages\exchangelib\services\common.py", line 644, in _paged_call
		pages = self._get_pages(payload_func, kwargs, expected_message_count)
	  File "C:\Users\Ram12405\PycharmProjects\pythonProject\venv\lib\site-packages\exchangelib\services\common.py", line 609, in _get_pages
		payload = payload_func(**kwargs)
	  File "C:\Users\Ram12405\PycharmProjects\pythonProject\venv\lib\site-packages\exchangelib\services\find_item.py", line 79, in get_payload
		finditem.append(restriction.to_xml(version=self.account.version))
	  File "C:\Users\Ram12405\PycharmProjects\pythonProject\venv\lib\site-packages\exchangelib\restriction.py", line 559, in to_xml
		return self.q.to_xml(folders=self.folders, version=version, applies_to=self.applies_to)
	  File "C:\Users\Ram12405\PycharmProjects\pythonProject\venv\lib\site-packages\exchangelib\restriction.py", line 346, in to_xml
		elem = self.xml_elem(folders=folders, version=version, applies_to=applies_to)
	  File "C:\Users\Ram12405\PycharmProjects\pythonProject\venv\lib\site-packages\exchangelib\restriction.py", line 469, in xml_elem
		elem.append(c.xml_elem(folders=folders, version=version, applies_to=applies_to))
	  File "C:\Users\Ram12405\PycharmProjects\pythonProject\venv\lib\site-packages\exchangelib\restriction.py", line 441, in xml_elem
		field_path = self._get_field_path(folders, applies_to=applies_to, version=version)
	  File "C:\Users\Ram12405\PycharmProjects\pythonProject\venv\lib\site-packages\exchangelib\restriction.py", line 415, in _get_field_path
		raise InvalidField("Unknown field path %r on folders %s" % (self.field_path, folders))
	exchangelib.fields.InvalidField: Unknown field path 'sender__EmailAddress' on folders [Inbox(Root(<exchangelib.account.Account object at 0x05AAECB8>, '[self]', 'root', 31, 0, 119, None,....)] 
	python-BaseException

Process finished with exit code -1
```

**Comment by thefedoration** [comment]
I've got the same issue. This is pretty important functionality for the package IMO, have you had any luck?

**Comment by thefedoration** [comment]
My observations are that querying `.filter(sender__icontains='somevalue')` works, but that filters on `Mailbox.name` and not `Mailbox.email_address`

This works as expected when there is no "name" on the sender, thus email_address gets populated into the "name" field. However, if the `Mailbox` has both name + email address, I don't see a way to filter for emails from a particular email address.

**Comment by Ram-Muljani** [comment]
instead of using

mails = account.inbox.filter(is_read=False, sender__icontains='SomeEmail@domain.co**m**', subject__contains='Please work')[:20]

i tried with 
mails = account.inbox.filter(is_read=False, sender__contains='SomeEmail@domain.co', subject__contains='Please work')[:20]

and it worked. I am going to stick with this filter for now. But no luck with Mailbox.name or Mailbox.emai_address

**Comment by ecederstrand** [comment]
When you use [FindItem](https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/finditem) to search for items in EWS, you create  a [Restriction](https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/restriction) element to contain the search criteria. That element takes a [Contains](https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/contains) element which again holds a [FieldURI](https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/fielduri) element.

The value of the FieldURI element can only be e.g. `message:Sender`, as far as I can see. You cannot specify it further down into name or email_address attributes. So we have to rely on whatever internal logic EWS uses to filter on this field.

**Comment by thefedoration** [comment]
Okay thank you for the explanation. I noticed that there is a `message:From` FieldURI option, but it's not available in `Message.FIELDS`. Would it be possible to add that field? Hoping that it contains the email and is a more reliable way of filtering on sender than `message.Sender`, which has inconsistent results.

Additionally, it would be really helpful to filter on the recipients (`message:ToRecipients`) of the email. There is a `Message.to_recipients` field, but it's `is_searchable` is `False`. What would it take to be able to search on that field? Unfortunately `Message.display_to` isn't reliable because like `Sender`, it sometimes shows the name and sometimes the email of the contact.

**Comment by ecederstrand** [comment]
`message:From` is available as the `author` field because `from` is a reserved word in Python.

`ToRecipients`  is not searchable because EWS returns an error on that field. I think EWS simply does not support searching on the field at all.

**Comment by thefedoration** [comment]
Got it - thanks Erik. I'll see if there's any difference between `author` and `sender` with the ability to search by email address specifically instead of the email/name combination.

Would indexed properties potentially be able to make a more targeted search query? It seemed to work for [searching contacts](https://github.com/ecederstrand/exchangelib/issues/162#issuecomment-843308245). 

That is quite the shame about `ToRecipients` not being searchable. I'll dig around and see if anybody else has solved this use-case with EWS, I'm sure I'm not the first person that has needed this functionality in their application.

**Comment by thefedoration** [comment]
I have some findings:
- `sender__icontains` filter works as expected when `mailbox_type='OneOff'`, not `mailbox_type='Mailbox'`
- using a string query like `.filter('from:"somedomain.com"')` works as expected for both `OneOff` and `Mailbox` mailbox types


Some screenshots:
`icontains` on a domain works, but returns `OneOff` emails only. `icontains` works with a `Mailbox` email type, but  only if the email address is an exact match. removing the last character of the email, or reducing it just to the domain, makes it such that no emails `Mailbox`  match.
<img width="1034" alt="mailbox" src="https://user-images.githubusercontent.com/6766645/119394081-69708f00-bc97-11eb-9386-22a2641dc1d6.png">

The above test was done with my domain, which is why the mailbox type is `Mailbox` for valid emails (the OneOff one was a transaction email alias). When filtering on `@gmail` addresses, they are all coming up as `OneOff` so the filtering works as expected.
<img width="958" alt="email" src="https://user-images.githubusercontent.com/6766645/119394355-b05e8480-bc97-11eb-9f1e-a16f4a7becb6.png">

Lastly, I discovered the string filtering. This appears to work as expected for both Mailbox and OneOff emails. Is this AQS syntax?
<img width="1040" alt="string" src="https://user-images.githubusercontent.com/6766645/119394805-3f6b9c80-bc98-11eb-839c-5fbe235f7b1e.png">

**Comment by ecederstrand** [comment]
Wow, that's a thorough investigation, @thefedoration ! I'm sure it will be of use for others.

Yes, the string filtering is AQS, which EWS supports. There's a reference here: https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/querystring-querystringtype exchangelib does not attempt to do any validation of the query string contents.

**Comment by ecederstrand** [comment]
I don't think there's anything we can do to improve exchangelib functionality here. Feel free to reopen if you disagree.
