### ISSUE TITLE
Not all mails are deleted

### ISSUE THREAD

**Issue by simon-spier0** [ecederstrand/exchangelib#931]
![2021-06-08_171823](https://user-images.githubusercontent.com/60992048/121216036-d0d63380-c880-11eb-9f14-f263baefe4ae.png)

See the attached screen. All mails older than month should be deleted but it didn't happen. If I limit a slice amount and not deleting any mails, the limit slice amount is iterated, however if I delete it while iterating, always is iterated and deleted random amount! No error is raised in this piece of code. Used the latest version (4.4.0)
Is this a bug in exchangelib or on exchange server?
Thank you.

**Comment by ecederstrand** [comment]
This is probably due to how paging works on the Exchange server. You request a bunch of items from the server. By default we get 100 items at a time. If you delete all items in the first page before fetching the next page, then it's very likely that items in the next page are no longer in direct succession of the first 100 items.

I'm not sure what the best solution for this is. You'll definitely get faster performance if you just do `mailbox.delete()` because that fetches far fewer data from the server, and will delete 1000 items at a time instead of 1 at a time. You could also collect all item IDs first, and *then* bulk delete these IDs:

```python
ids = list(account.inbox.filter(...).only('id', 'changekey'))
account.bulk_delete(ids)
```

**Comment by simon-spier0** [comment]
Yes, that's it! Thank you for this nice solution. :)
